package golang

import (
	"context"
	"errors"
	"go/scanner"
	"go/token"
	"io"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/jonasalessi/cdd-lint/internal/analyze"
)

// TestSyntaxError (TC-P1): a file that does not parse is a warning, not a
// failed run. The position is the one go/parser reports for
// `expected ')', found '{'`, pinned literally so a toolchain change shows up
// here.
func TestSyntaxError(t *testing.T) {
	a := newTestAnalyzer(t)
	res, err := a.Analyze(context.Background(), "broken"+extGo, readFixture(t, "broken.go.txt"))
	require.NoError(t, err)
	require.Empty(t, res.Units)
	require.Equal(t, []string{"syntax error at 3:9"}, res.Warnings)
}

// TestSyntaxWarningFallback (TC-P2): every go/parser failure observed so far
// is a scanner.ErrorList whose first error carries a position, so the 1:1
// fallback is unreachable from real Go source and is asserted through the
// helper the analyzer calls.
func TestSyntaxWarningFallback(t *testing.T) {
	noList := errors.New("read source: broken")
	noPosition := scanner.ErrorList{&scanner.Error{Pos: token.Position{}, Msg: "no position"}}
	for name, err := range map[string]error{
		"not an error list":        noList,
		"first error unpositioned": noPosition,
		"empty error list":         scanner.ErrorList{},
	} {
		t.Run(name, func(t *testing.T) {
			require.Equal(t, "syntax error at 1:1", syntaxWarning(err))
		})
	}
}

// TestEmptyFile (TC-P3): zero bytes short-circuit before go/parser can say
// `expected 'package', found 'EOF'`.
func TestEmptyFile(t *testing.T) {
	a := newTestAnalyzer(t)
	res, err := a.Analyze(context.Background(), "empty"+extGo, readFixture(t, "empty.go.txt"))
	require.NoError(t, err)
	require.Empty(t, res.Units)
	require.Empty(t, res.Warnings)
}

// TestWhitespaceOnlyFile (TC-P4): whitespace is as empty as no bytes at all.
func TestWhitespaceOnlyFile(t *testing.T) {
	a := newTestAnalyzer(t)
	res, err := a.Analyze(context.Background(), "blank"+extGo, []byte("  \t\n\r\n \n"))
	require.NoError(t, err)
	require.Empty(t, res.Units)
	require.Empty(t, res.Warnings)
}

// TestGeneratedFile (TC-P5): a Code-generated header before the package
// clause yields no units and no warnings, even though the file parses. The
// same marker after the package clause is an ordinary comment; the units it
// carries arrive with the unit extraction.
func TestGeneratedFile(t *testing.T) {
	res := analyzeFixture(t, "generated"+extGo)
	require.Empty(t, unitNames(res))
	require.Empty(t, res.Warnings)

	const lateMarker = "package app\n\n// Code generated by hand. DO NOT EDIT.\n\n" +
		"type Message struct {\n\tName string\n}\n"
	require.Empty(t, analyzeSource(t, lateMarker).Warnings)
}

// TestHeaderOnlyFile (TC-P6): a package clause, an import and a top-level
// var hold nothing to measure, which is not a warning.
func TestHeaderOnlyFile(t *testing.T) {
	res := analyzeFixture(t, "header_only"+extGo)
	require.Empty(t, unitNames(res))
	require.Empty(t, res.Warnings)
}

// TestUnsupportedExtension (TC-P7) refuses to guess: a Kotlin file, a
// near-miss extension, a path without one and a fixture kept as text are all
// errors naming the path and the extension.
func TestUnsupportedExtension(t *testing.T) {
	a := newTestAnalyzer(t)
	for _, p := range []string{"a.kt", "a.golang", "a", "a.go.txt"} {
		res, err := a.Analyze(context.Background(), p, []byte("package app\n"))
		require.ErrorContains(t, err, p, p)
		require.Empty(t, res.Units, p)
	}
	_, err := a.Analyze(context.Background(), "a.kt", []byte("package app\n"))
	require.ErrorContains(t, err, `".kt"`)
}

// TestUppercaseExtension (TC-P8): the extension test is case-insensitive.
func TestUppercaseExtension(t *testing.T) {
	a := newTestAnalyzer(t)
	for _, p := range []string{"A.GO", "A.Go"} {
		res, err := a.Analyze(context.Background(), p, []byte("package app\n\ntype A struct{}\n"))
		require.NoError(t, err, p)
		require.Empty(t, res.Warnings, p)
	}
}

// TestCanceledContext (TC-P9) stops before parsing instead of running to
// completion.
func TestCanceledContext(t *testing.T) {
	a := newTestAnalyzer(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	res, err := a.Analyze(ctx, "header_only"+extGo, readFixture(t, "header_only"+extGo))
	require.ErrorIs(t, err, context.Canceled)
	require.ErrorContains(t, err, "header_only")
	require.Empty(t, res.Units)
}

// TestAnalyzerHoldsNoResource (TC-P12): go/parser allocates nothing to
// release, so the analyzer is not an io.Closer and the pipeline has nothing
// to close.
func TestAnalyzerHoldsNoResource(t *testing.T) {
	_, ok := NewAnalyzer(analyze.Options{}).(io.Closer)
	assert.False(t, ok, "the Go analyzer must hold no closable resource")
}

// TestReanalyzeIsStable (TC-P12): one analyzer over the same file many
// times, and two analyzers over it, agree — each call builds its own
// token.FileSet, so nothing accumulates between them.
func TestReanalyzeIsStable(t *testing.T) {
	a := newTestAnalyzer(t)
	src := readFixture(t, "header_only"+extGo)
	first, err := a.Analyze(context.Background(), "header_only"+extGo, src)
	require.NoError(t, err)
	for range 200 {
		res, err := a.Analyze(context.Background(), "header_only"+extGo, src)
		require.NoError(t, err)
		require.Equal(t, first, res)
	}
	other, err := newTestAnalyzer(t).Analyze(context.Background(), "header_only"+extGo, src)
	require.NoError(t, err)
	require.Equal(t, first, other)
}
